//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement {
    
    
    public partial class StudentManagement {
        
        protected Controls.Banner Banner;
        
        protected System.Web.UI.WebControls.SiteMapDataSource siteMapData;
        
        protected System.Web.UI.WebControls.Repeater menu;
        
        protected Controls.Navigation Navigation;
        
        protected Controls.Notifications Notifications;
        
        protected Controls.Classes Classes;
        
        protected Controls.Grades Grades;
        
        protected System.Web.UI.WebControls.ContentPlaceHolder head;
        
        protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder1;
    }
}
